### ISSUE TITLE
Modul updates every seconds

### ISSUE THREAD

**Issue by Logan-80** [KristjanESPERANTO/MMM-PublicTransportHafas#131]
Hello, my ad is reloaded every second. Also the option updatesEvery shows no function. How can I negotiate frequent reloads? Is this already known to anyone?

**Module config**
```js
{
  module: "MMM-PublicTransportHafas",
  position: "bottom_right",
  
  config: {
    stationID: "954202",             // Replace with your stationID!
    stationName: "Raschwitzer Str.",   		// Replace with your station name!
    direction: "955791",                    // Show only departures heading to this station. (A station ID.)
    ignoredLines: [],                 // Which lines should be ignored? (comma-separated list of line names)
    excludedTransportationTypes: ["bus"],  // Which transportation types should not be shown on the mirror? (comma-separated list of types) possible values: StN for tram, BuN for bus, s for suburban
    timeToStation: 10,                // How long do you need to walk to the next Station?

    showColoredLineSymbols: true,     // Want colored line symbols?
    useColorForRealtimeInfo: true,    // Want colored real time information (timeToStation, early)?
    showTableHeadersAsSymbols: true,  // Table Headers as symbols or text?
    maxUnreachableDepartures: 0,      // How many unreachable departures should be shown?
    maxReachableDepartures: 3,        // How many reachable departures should be shown?
    customLineStyles: "leipzig",      // Prefix for the name of the custom css file. ex: Leipzig-lines.css (case sensitive)
    showOnlyLineNumbers: false,       // Display only the line number instead of the complete name, i. e. "11" instead of "STR 11"
	tableHeaderOrder: [ "time", "line", "direction" ],
	showOnlyLineNumbers: true,
  }
}
```

**Screenshots**

![1](https://user-images.githubusercontent.com/59292460/211210213-06958829-f194-4623-b392-8713d7cb4516.png)
![2](https://user-images.githubusercontent.com/59292460/211210218-29171766-6b31-43ac-84c0-dce42c605693.png)

Based on the time you can see the short update time. In between, several updates were made.

**Additional context**
I had the same thing with the raywo module. Unfortunately I have the same error with the new module.

many thanks, Lars

**Comment by KristjanESPERANTO** [comment]
Interesting. Your configuration works fine for me. Updates only come every 120 seconds.

I suspect that another module might be causing the updates. Can you please test the following: In your configuration, remove all modules except for this one and then observe whether the error occurs again.

**Comment by KristjanESPERANTO** [comment]
In your configuration there are two entries of `showOnlyLineNumbers`. you should remove one of them. But that's just a cosmetic thing, it shouldn't cause any error.

**Comment by Logan-80** [comment]
Hello, thanks for the answer. If I disable all modules it works as desired. As soon as I activate a module like the clock, the weather or OpenHab, the update starts again. Where could I look for the error? I can't even say since when the error has existed. But it worked fine for a long time. Many Thanks.

**Comment by KristjanESPERANTO** [comment]
That's odd... Let's gather some information to find out.

Which MagicMirror version are you using? Please run `npm run config:check` in your MagicMirror folder. This command also checks if your config contains syntax errors.

Which node version are you using? Run `node -v`.

Which npm version are you using? Run `npm -v`.

**Comment by Logan-80** [comment]
Hello,

`npm run config:check`

> magicmirror@2.22.0 config:check
> node js/check_config.js

[10.01.2023 18:06.25.072] [INFO]  Checking file...  /home/openhabian/MagicMirror/config/config.js
[10.01.2023 18:06.25.158] [INFO]  Your configuration file doesn't contain syntax errors :)

`node -v`
v14.21.1

`npm -v`
9.2.0

**Comment by KristjanESPERANTO** [comment]
This module needs at least node 16. I recommend installing that. I'm surprised you were able to install it at all. Actually, you should have gotten an error message when you did `npm install --omit=dev`.

Point 1 of the MagicMirror installation guide tells you how to install node 16:
<https://docs.magicmirror.builders/getting-started/installation.html#manual-installation>

**Comment by Logan-80** [comment]
Update was successful, thanks for the tip. Unfortunately without success, the display continues to update every second.

**Comment by KristjanESPERANTO** [comment]
That's an interesting case. Okay, I need more information:

Which kernel release are you using? Run`uname -a`.

Which distro release are you using?  Run `lsb_release -a`.

Please show me your whole configuration (without keys or credentials).

**Comment by Logan-80** [comment]
`uname -a`
Linux OpenHab3 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

`lsb_release -a`
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

What configuration should I post here?

**Comment by KristjanESPERANTO** [comment]
Your `config.js`.

**Comment by Logan-80** [comment]
Here my configuration:

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "192.168.xxx.xx", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8099,
	ipWhitelist: ["..."], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "de",
	timeFormat: 24,
	units: "metric",

	modules: [
	// HABPanel anzeigen oben links
	{
    module: 'MMM-Openhab',
    position: 'top_left',                   // Best in left or right regions
    config: { 
			url: "http://192.168.xxx.xx:8080/habpanel/index.html#/view/Heating"   // url of your Openhab sitemap
			}
	},
	// Uhr anzeigen unten links	
	{
	module: "clock",
	position: "bottom_left",
	},
	{
	module: "calendar",
	header: "Kalender",
	position: "top_right",
	config: 
		{
			maximumEntries: 7,					// maximale Einträge
			maximumNumberOfDays: 14,			// maximale Tage
			maxTitleLength: 10,					// maximale Länge der Einträge bis Zeilenumbruch
			wrapEvents: true,					// Zeilenumbruch
			dateFormat: "DoMM.",				// Datumformat 
			fullDayEventDateFormat: "DoMM.",	// Datumformat
			timeFormat: "absolute",				// Datumformat
		calendars: 
			[
				{
				symbol: "calendar-check-o ",
				url: "https://calendar.google.com/calendar/ical/...group.calendar.google.com/private-.../basic.ics"
				}
			]
		}
	},
	// Wetter heute und 3 Tage im Vorraus	
		{
			disabled: false,
			module: "weather",
			position: "bottom_center",
			header: "Wetter aktuell",
			config: {
				type: "current",
				location: "Leipzig",
				locationID: "6548737",  
				apiKey: "861bba989c9dc278555de239a48b7b6d",
				showWindDirectionAsArrow: true,
				showHumidity: true,
				showFeelsLike: false
				}
		},
		{
			disabled: false,
			module: "weather",
			position: "bottom_center",
			header: "Wetter in",
			config: {
				type: "forecast",
				location: "Leipzig",
				locationID: "6548737",  
				apiKey: "861bba989c9dc278555de239a48b7b6d",
				showWindDirectionAsArrow: true,
				showHumidity: true,
				showFeelsLike: false
				}
		},
// Dürrstr. in Richtung MoritzHof	
	{
  module: "MMM-PublicTransportHafas",
  position: "bottom_right",
  
  config: {
    stationID: "964677",        // Replace with your stationID! 000964050(Dankwartstr.);964677(Dürrstr.);954202(Raschwitzer Str.)
    stationName: "Dürrstr.",   // Replace with your station name!
    updatesEvery: 120,
	direction: "000957432",           // Show only departures heading to this station. (A station ID.)
    ignoredLines: [],                 // Which lines should be ignored? (comma-separated list of line names)
    excludedTransportationTypes: [],  // Which transportation types should not be shown on the mirror? (comma-separated list of types) possible values: StN for tram, BuN for bus, s for suburban
    timeToStation: 5,                 // How long do you need to walk to the next Station?

    showColoredLineSymbols: true,     // Want colored line symbols?
    useColorForRealtimeInfo: true,    // Want colored real time information (timeToStation, early)?
    showTableHeadersAsSymbols: true,  // Table Headers as symbols or text?
    maxUnreachableDepartures: 0,      // How many unreachable departures should be shown?
    maxReachableDepartures: 2,        // How many reachable departures should be shown?
    customLineStyles: "leipzig",      // Prefix for the name of the custom css file. ex: Leipzig-lines.css (case sensitive)
    showOnlyLineNumbers: false,       // Display only the line number instead of the complete name, i. e. "11" instead of "STR 11"
	tableHeaderOrder: [ "time", "line", "direction" ],
	showOnlyLineNumbers: true,
  }
},	
	// MoritzHof Richtung Hbf
	{
  module: "MMM-PublicTransportHafas",
  position: "bottom_right",
  
  config: {
    stationID: "954677",             // Replace with your stationID! Lössnig(000954677), Moritzhof(000957432)
    stationName: "Lössnig",   		// Replace with your station name!
    direction: "956291",           // Show only departures heading to this station. (A station ID.)
    ignoredLines: [],                 // Which lines should be ignored? (comma-separated list of line names)
    excludedTransportationTypes: [],  // Which transportation types should not be shown on the mirror? (comma-separated list of types) possible values: StN for tram, BuN for bus, s for suburban
    timeToStation: 10,                // How long do you need to walk to the next Station?

    showColoredLineSymbols: true,     // Want colored line symbols?
    useColorForRealtimeInfo: true,    // Want colored real time information (timeToStation, early)?
    showTableHeadersAsSymbols: true,  // Table Headers as symbols or text?
    maxUnreachableDepartures: 0,      // How many unreachable departures should be shown?
    maxReachableDepartures: 3,        // How many reachable departures should be shown?
    customLineStyles: "leipzig",      // Prefix for the name of the custom css file. ex: Leipzig-lines.css (case sensitive)
    showOnlyLineNumbers: false,       // Display only the line number instead of the complete name, i. e. "11" instead of "STR 11"
	tableHeaderOrder: [ "time", "line", "direction" ],
	showOnlyLineNumbers: true,
  }
},	

	// Raschwitzer Str. Richtung Hbf
	{
  module: "MMM-PublicTransportHafas",
  position: "bottom_right",
  
  config: {
    stationID: "954202",             // Replace with your stationID!
    stationName: "Raschwitzer Str.",   		// Replace with your station name!
    direction: "955791",                    // Show only departures heading to this station. (A station ID.)
    ignoredLines: [],                 // Which lines should be ignored? (comma-separated list of line names)
    excludedTransportationTypes: ["bus"],  // Which transportation types should not be shown on the mirror? (comma-separated list of types) possible values: StN for tram, BuN for bus, s for suburban
    timeToStation: 10,                // How long do you need to walk to the next Station?

    showColoredLineSymbols: true,     // Want colored line symbols?
    useColorForRealtimeInfo: true,    // Want colored real time information (timeToStation, early)?
    showTableHeadersAsSymbols: true,  // Table Headers as symbols or text?
    maxUnreachableDepartures: 0,      // How many unreachable departures should be shown?
    maxReachableDepartures: 3,        // How many reachable departures should be shown?
    customLineStyles: "leipzig",      // Prefix for the name of the custom css file. ex: Leipzig-lines.css (case sensitive)
    showOnlyLineNumbers: false,       // Display only the line number instead of the complete name, i. e. "11" instead of "STR 11"
	tableHeaderOrder: [ "time", "line", "direction" ],
	showOnlyLineNumbers: true,
  }
},	

	// S-Bahn Richtung Hbf
	{
  module: "MMM-PublicTransportHafas",
  position: "bottom_right",
  
  config: {
    stationID: "008010206",             // Replace with your stationID!
    stationName: "S-Bahn",   		// Replace with your station name!
    direction: "008010205",                    // Show only departures heading to this station. (A station ID.)
    ignoredLines: [],                 // Which lines should be ignored? (comma-separated list of line names)
    excludedTransportationTypes: ["tram", "bus"],  // Which transportation types should not be shown on the mirror? (comma-separated list of types) possible values: StN for tram, BuN for bus, s for suburban
    timeToStation: 10,                // How long do you need to walk to the next Station?

    showColoredLineSymbols: true,     // Want colored line symbols?
    useColorForRealtimeInfo: true,    // Want colored real time information (timeToStation, early)?
    showTableHeadersAsSymbols: true,  // Table Headers as symbols or text?
    maxUnreachableDepartures: 0,      // How many unreachable departures should be shown?
    maxReachableDepartures: 3,        // How many reachable departures should be shown?
    customLineStyles: "leipzig",      // Prefix for the name of the custom css file. ex: Leipzig-lines.css (case sensitive)
    showOnlyLineNumbers: false,       // Display only the line number instead of the complete name, i. e. "11" instead of "STR 11"
	tableHeaderOrder: [ "time", "line", "direction" ],
	showOnlyLineNumbers: true,
  }
},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by KristjanESPERANTO** [comment]
Your configuration works perfectly on my side. Although I have not installed all your modules. Can you test to confirm whether the following configuration causes the same problems?

```js
let config = {
  address: "localhost",
  port: 8099,
  ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],
  language: "de",
  timeFormat: 24,
  units: "metric",
  modules: [
    // Uhr anzeigen unten links	
    {
      module: "clock",
      position: "bottom_left"
    },
    // Dürrstr. in Richtung MoritzHof	
    {
      module: "MMM-PublicTransportHafas",
      position: "bottom_right",
      config: {
        stationID: "964677",
        stationName: "Dürrstraße",
        updatesEvery: 120,
        direction: "957432",
        ignoredLines: [],
        excludedTransportationTypes: [],
        timeToStation: 5,
        showColoredLineSymbols: true,
        useColorForRealtimeInfo: true,
        showTableHeadersAsSymbols: true,
        maxUnreachableDepartures: 0,
        maxReachableDepartures: 2,
        customLineStyles: "leipzig",
        showOnlyLineNumbers: false,
        tableHeaderOrder: ["time", "line", "direction"]
      }
    },
    // MoritzHof Richtung Hbf
    {
      module: "MMM-PublicTransportHafas",
      position: "bottom_right",
      config: {
        stationID: "954677",
        stationName: "Lössnig",
        direction: "956291",
        ignoredLines: [],
        excludedTransportationTypes: [],
        timeToStation: 10,
        showColoredLineSymbols: true,
        useColorForRealtimeInfo: true,
        showTableHeadersAsSymbols: true,
        maxUnreachableDepartures: 0,
        maxReachableDepartures: 3,
        customLineStyles: "leipzig",
        showOnlyLineNumbers: false,
        tableHeaderOrder: ["time", "line", "direction"]
      }
    },
    // Raschwitzer Str. Richtung Hbf
    {
      module: "MMM-PublicTransportHafas",
      position: "bottom_right",
      config: {
        stationID: "954202",
        stationName: "Raschwitzer Str.",
        direction: "955791",
        ignoredLines: [],
        excludedTransportationTypes: ["bus"],
        timeToStation: 10,
        showColoredLineSymbols: true,
        useColorForRealtimeInfo: true,
        showTableHeadersAsSymbols: true,
        maxUnreachableDepartures: 0,
        maxReachableDepartures: 3,
        customLineStyles: "leipzig",
        showOnlyLineNumbers: false,
        tableHeaderOrder: ["time", "line", "direction"]
      }
    },
    // S-Bahn Richtung Hbf
    {
      module: "MMM-PublicTransportHafas",
      position: "bottom_right",
      config: {
        stationID: "8010206",
        stationName: "S-Bahn",
        direction: "8010205",
        ignoredLines: [],
        excludedTransportationTypes: ["tram", "bus"],
        timeToStation: 10,
        showColoredLineSymbols: true,
        useColorForRealtimeInfo: true,
        showTableHeadersAsSymbols: true,
        maxUnreachableDepartures: 0,
        maxReachableDepartures: 3,
        customLineStyles: "leipzig",
        showOnlyLineNumbers: false,
        tableHeaderOrder: ["time", "line", "direction"]
      }
    }
  ]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") { module.exports = config; }
```

If the problems also occur with this, I'm slowly running out of ideas and would suggest reinstalling MagicMirror.

**Comment by Logan-80** [comment]
Hello, I can not understand the error either. Reinstall=same error; new configuration=same error. I have now installed it as Docker on my NAS and it works there. Thanks for your support.

**Comment by KristjanESPERANTO** [comment]
Strange. I close the issue for now. Have fun with your mirror! :smiley:

**Comment by Rene1695** [comment]
Hi,

it seems like I have exactly the same issue :( I am running MagicMirror in Docker on my Unraid server. I set the refresh rate to 60 seconds. After 60 seconds the module is refreshing and then after like 10 seconds it is refreshing again:


![IMG_9219](https://github.com/user-attachments/assets/a62b33d1-24f1-47ff-a118-4d3ddd424d41)

![IMG_9220](https://github.com/user-attachments/assets/f9e1f56d-fee1-47e2-acad-9e52290e4429)

` npm run config:check`

```
> magicmirror@2.28.0 config:check
> node js/check_config.js

[2024-09-16 18:03:27.291] [INFO]  Checking file...  /magicmirror2/config/config.js 
[2024-09-16 18:03:27.324] [INFO]  Your configuration file doesn't contain syntax errors :) 
[2024-09-16 18:03:27.324] [INFO]  Checking modules structure configuration...  
[2024-09-16 18:03:27.376] [INFO]  Your modules structure configuration doesn't contain errors :)
 ```
`node -v`
```
v18.20.2
```

`npm -v`
```
10.5.0
```

`uname -a`
```
Linux ed678c0ec11f 6.1.106-Unraid #1 SMP PREEMPT_DYNAMIC Wed Aug 21 23:36:07 PDT 2024 x86_64 GNU/Linux
```

`lsb_release -a`
```
bash: lsb_release: command not found

Unraid OS 6.12.13
```

`config.js`
```

var config = {
	address: "0.0.0.0", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out or empty, is "localhost"
	port: 8080,
	ipWhitelist: [],
	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "de",
	timeFormat: 24,
	units: "metric",
	serverOnly:  "true" ,
			     // local for armv6l processors, default
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device

	modules: [
	
		{
			module: "alert",
		},
	
//############################# LEFT #######################################################################################################################################################################
		{
			module: "clock",
			position: "top_left"
		},

		// Google Calender
		{
			module: "calendar",
			position: "top_left", // This can be any of the regions. Best results in left or right regions.
			header: "Termine",
			config: {
				colored: true,
				coloredSymbolOnly: true,
				maximumEntries: 8,
				timeFormat: "relative",
				excludedEvents: [],
				calendars: [

					{
						url: "",
						symbol: 'house-chimney-window',
						color: "rgb(229,171,54)",
						
					},
					{
						url: "",
						symbol: 'birthday-cake',
						color: "rgb(255,0,0)",
						
					},
					{
						url: "",
						symbol: 'building',
						color: "rgb(166,133,34)",
							
					},
					{
						url: "",
						symbol: 'people-roof',
						color: "rgb(68,118,109)",
							
					},
					// RocketBeans
					{
						url: "",
						symbolClassName: "fab fa-fw fa-",
						symbol: 'twitch',
						color: "rgb(143,83,242)",
												
					},
					// Space Launches
					{
						url: "https://calendar.google.com/calendar/ical/6cfa7f15a8ed8690f60258dd0ac002179bae253ce30168bd0bdfa494e3c0bd88%40group.calendar.google.com/private-c742b7b31c7959ba83c558b44e4808b0/basic.ics",
						symbolClassName: "fas fa-fw fa-",
						symbol: 'shuttle-space',
						color: "rgb(255,255,255)",
						
												
					},
	

						],
					},
		  },
		{
			
			module: 'MMM-GrafanaChart',
			position: 'bottom_left',   // This can be any of the regions.
			header: "Stromverbrauch",
			config: {
					url: "", // see below on how to get the URL from Grafana
					width: "140%", // Optional. Default: 100%
					height: "100px", // Optional. Default: 100%
					scrolling: "no", // Optional. Default: no
					refreshInterval: 1800 //Optional. Default: 900 = 1/4 hour
					}
		},

		{ 
			  
				module: 'MMM-GrafanaChart',
				position: 'bottom_left',   // This can be any of the regions.
				config: {
						url: "", // see below on how to get the URL from Grafana
						width: "140%", // Optional. Default: 100%
						height: "300px", // Optional. Default: 100%
						scrolling: "no", // Optional. Default: no
						refreshInterval: 1800 //Optional. Default: 900 = 1/4 hour
						}
		},


		{
			
			module: 'MMM-GrafanaChart',
			position: 'bottom_left',   // This can be any of the regions.
			config: {
					url: "", // see below on how to get the URL from Grafana
					width: "140%", // Optional. Default: 100%
					height: "110px", // Optional. Default: 100%
					scrolling: "no", // Optional. Default: no
					refreshInterval: 1800 //Optional. Default: 900 = 1/4 hour
					}
	},


//############################# RIGHT #######################################################################################################################################################################

	
		 // Aktuelles Wetter
		{
			module: "weather",
			position: "top_right", // This can be any of the regions.
			header: "Aktuell",
			timeFormat: 24,
			// Best results in left or right regions.
			config: {
				weatherProvider: "openmeteo",
				apiBase: "https://api.open-meteo.com/v1",
				lat: 0,
				lon: 0,
				type: "current",
				location: "Berlin",
				locationID: "0",
				apiKey: "0"
			  
					},
		},
		  

		  // Wetter-Vorhersage

		{
			module: "weather",
			position: "top_right", // This can be any of the regions.
			header: "Vorhersage",
			timeFormat: 24,
			// Best results in left or right regions.
			config: {
				weatherProvider: "openmeteo",
				apiBase: "https://api.open-meteo.com/v1",
				lat: 0,
				lon: 0,
				colored: true,
				type: "forecast",
				location: "Berlin",
				locationID: "0",
				apiKey: "0"
			  
					},
		},
		  
		  // Regenradar

		{
			module: "MMM-RAIN-MAP",
			position: "top_right",
			header: "Regenradar",
			config: {
				animationSpeedMs: 400,
				colorScheme: 2,
				colorizeTime: false,
				defaultZoomLevel: 8,
				displayTime: true,
				displayTimeline: true,
				displayClockSymbol: true,
				displayHoursBeforeRain: -1,
				extraDelayLastFrameMs: 1000,
				extraDelayCurrentFrameMs: 0,
				markers: [
					{ lat: 0, lng: 0, color: "green" },
				],
				mapPositions: [
					{ lat: 53.063088, lng: 8.781509, zoom: 10, loops: 1 },
					{ lat: 53.063088, lng: 8.781509, zoom: 8, loops: 1 },
					{ lat: 53.063088, lng: 8.781509, zoom: 6, loops: 1 },

				],
				mapUrl: "https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png",
				mapHeight: "320px", // must be a pixel value (no percent)
				mapWidth: "360px", // must be a pixel value (no percent)
				maxHistoryFrames: -1,
				maxForecastFrames: -1,
				substitudeModules: [],
				updateIntervalInSeconds: 300,

					}
		},

		{
			module: "MMM-PublicTransportHafas",
			position: "top_right",
		  
			config: {
			  // Departures options
			  stationID: "117513",                   // Replace with your stationID!
			  stationName: "Brinkum, Marktplatz", // Replace with your station name!
			  direction: "",                    // Show only departures heading to this station. (A station ID.)
			  excludedTransportationTypes: [],  // Which transportation types should not be shown on the mirror? (comma-separated list of types) possible values: "tram", "bus", "suburban", "subway", "regional" and "national"
			  ignoredLines: ["Bus 55"],                 // Which lines should be ignored? (comma-separated list of line names)
			  timeToStation: 8,                // How long do you need to walk to the next Station?
			  updatesEvery: 60,
			  timeInFuture: 90,
			  tableHeaderOrder: [ "time", "line", "direction" ],
		  
			  // Look and Feel
			  displayLastUpdate: true,          // Display the last time of module update.
			  maxUnreachableDepartures: 0,      // How many unreachable departures should be shown?
			  maxReachableDepartures: 6,        // How many reachable departures should be shown?
			  showColoredLineSymbols: true,     // Want colored line symbols?
			  customLineStyles: "",             // Prefix for the name of the custom css file. ex: Leipzig-lines.css (case sensitive)
			  showOnlyLineNumbers: false,       // Display only the line number instead of the complete name, i. e. "11" instead of "STR 11"
			  showTableHeadersAsSymbols: true,  // Table Headers as symbols or text?
			  useColorForRealtimeInfo: true,     // Want colored real time information (timeToStation, early)?
			  displayLastUpdateFormat: "HH:mm:ss"
			}
		  },
	


//############################# BOTTOM #######################################################################################################################################################################

	// Nachrichten
		{
		module: "newsfeed",
		position: "bottom_center", // This can be any of the regions. Best results in center regions.
		config: {
		  // The config property is optional.
		  // If no config is set, an example calendar is shown.
		  // See 'Configuration options' for more information.
	
		  feeds: [
			{
			  title: "Tagesschau",
			  url: "http://www.tagesschau.de/xml/rss2",
			},
		  		],
				},
	  	},

		// Add here new modules
			
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

```

Sorry for re-opening. But maybe you have some additional tipps for me. I don't want to re-install my whole setup :D

**Comment by KristjanESPERANTO** [comment]
Thank you for the good issue report. But I still can't see this behavior on my systems. And your config runs on my test computer without any problems :thinking: 

Please deactivate all other modules and see if it still occurs.

**Comment by Rene1695** [comment]
Hi thanks For the reply :) it seems like the issue has equalized over time. When I came from work I saw that everything now is working as it should. There is only one refresh as defined in the parameter.

Strangle now it got every 15-20 minutes the same error messages like in #138 :( 

I do not use the Carousel module. Tomorrow I have more time and will do some testing. I will report it here. Besides this, do you have any more information on this error message?

Thank you and have a nice evening :)

**Comment by KristjanESPERANTO** [comment]
> it seems like the issue has equalized over time. When I came from work I saw that everything now is working as it should. There is only one refresh as defined in the parameter.

Odd :thinking: 

> Strangle now it got every 15-20 minutes the same error messages like in https://github.com/KristjanESPERANTO/MMM-PublicTransportHafas/issues/138 :(

Where do you see this message? In the terminal or in the module?

You may have an unstable internet connection. Are you using WLAN?

Please see if the problem(s) also occur when you use the vbn profile (you also need to use a different stationID). Like this:

```js
		{
			module: "MMM-PublicTransportHafas",
			position: "top_left",
			config: {
			    hafasProfile: "vbn",
			    stationID: "9017513",
			    stationName: "Brinkum, Marktplatz",
			  
                ....
```

**Comment by KristjanESPERANTO** [comment]
Closing since there was no feedback. If you still have issues, let me know :slightly_smiling_face:
