### ISSUE TITLE
query_stations error

### ISSUE THREAD

**Issue by 111wolf111** [KristjanESPERANTO/MMM-PublicTransportHafas#133]
Hi,
I've had the module running for a couple of years now and love it,
but I'm not sure if I'm doing something wrong or if my mirror is not setup right but I went to add a new station id and am getting this error when running the query_stations

```bash
/home/pi/MagicMirror/modules/MMM-PublicTransportHafas/convenience/query_stations.mjs:2
import { createClient } from "hafas-client";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

when you get the time, could you please look into it or let me know if I'm doing something wrong...
Thanx

**Comment by KristjanESPERANTO** [comment]
Hi @111wolf111, which node version are you using? Run `node -v` to find out.

**Comment by 111wolf111** [comment]
Hi,
node V10.24.1
and 
npm 6.14.12

Last time I updated them I screwed up something cause it broke the MM install so haven't updated them in a while...

**Comment by KristjanESPERANTO** [comment]
This module needs at least node 16. I recommend installing that. I'm surprised you were able to install the module at all. Actually, you should have gotten an error message when you did `npm install --omit=dev`.

Point 1 of the MagicMirror installation guide tells you how to install node 16:
https://docs.magicmirror.builders/getting-started/installation.html#manual-installation

After the node update run `npm install --omit=dev` in the modules folder.

**Comment by 111wolf111** [comment]
that did the trick.....Thanx for your time....
and thanx for the module...

**Comment by KristjanESPERANTO** [comment]
@111wolf111: Did you delete your last post? I got an email from the post but I don't see it here.

**Comment by 111wolf111** [comment]
yea, sorry had to go to work today....
updating node did the trick, the mirror is now restarting, thought it was to do with the module but looks like it's pm2 that is restarting so have to look into that......thanx for your help and time... and for the module....

**Comment by KristjanESPERANTO** [comment]
Good to hear it's working now :smiley: 

I'm closing the issue. If there is anything else, let me know here or open a new issue.
