### ISSUE TITLE
custom css will not work for square re-lines + feedback on the  csss for düsseldorf

### ISSUE THREAD

**Issue by Dom1n1c** [KristjanESPERANTO/MMM-PublicTransportHafas#134]
**Bug description**
I tried to create an own rrx-lines.css, but am struggeling with the format:
![image](https://user-images.githubusercontent.com/8407566/213917797-a268ca5a-8e30-4a16-8b19-aae5d5d9c4d1.png)

**Module config**
```
.re1, .re5 {
  background-color: #FF8C00;  /* orange-ish background */
  border-radius: 1.25rem;
  color: black;
  width: 2em;
}
```
**Additional context**
I noticed that the lines in the [duesseldorf-lines.css](https://github.com/KristjanESPERANTO/MMM-PublicTransportHafas/blob/main/css/duesseldorf-lines.css) are missing some lines:
Subways: U70, U71, U72, U73, U74, U75, U76, U77, U78, U79, U83
Trams: 701, 704, 705, 706, 707, 708, 709
RE: RE1, RE5
Trains (DB): S1, S11, S28, S6, S68, S8

Busses: 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 749, 751, 752, 754, 756, 757, 758, 759, 760, 776, 778, 779, 780, 781, 782, 784, 785, 788, 789, 827, 828, 829, 830, 833, 834, 835, 836, 841, 862, 863, 864, 891, 894, 896
Metro busses (faster): M1, M2, M3
Fast busses: (SB): SB50, SB51, SB52, SB53, SB55, SB57, SB59, SB85
Night lines: NE1, NE2, NE3, NE4, NE5, NE6, NE7, NE8

([Source: City of Düsseldorf](https://www.duesseldorf.de/verkehrsmanagement/mit-bus-und-bahn/stadt-u-bahnnetz.html))
And i got those lines also line-overview documents of the local company (rheinbahn): https://www.rheinbahn.de/fahren/fahrplanauskunft/liniennetzplaene

**Comment by Dom1n1c** [comment]
There is a whitespace in the line "RE 1" and "RE 5"
Is it possible to replace the linename?
![image](https://user-images.githubusercontent.com/8407566/213925741-34743b11-f1e2-426d-9f3a-09744b8cce54.png)

**Comment by Dom1n1c** [comment]
I changed the duesseldorf-lines according to the linienplan of the operator (rheinbahn)
Feel free to use those values in your environment:
[Duesseldorf.pdf](https://github.com/KristjanESPERANTO/MMM-PublicTransportHafas/files/10475247/Duesseldorf.pdf)

```
.str701 {
  background-color: #f58221;
  color: white;
}
.str704 {
  background-color: #bf1e23;
  color: white;
}
.str705 {
  background-color: #bd1b8e;
  color: white;
}
.str706 {
  background-color: #ee1c25;
  color: white;
}
.str707 {
  background-color: #781d7d;
  color: white;
}
.str708 {
  background-color: #f698b2;
  color: white;
}
.str709 {
  background-color: #ee4c9c;
  color: white;
}

.busm1,
.busm2,
.busm3 {
  background-color: #1db056;
  color: white;
}

.bus721,
.bus722,
.bus723,
.bus724,
.bus725,
.bus726,
.bus727,
.bus728,
.bus729,
.bus730,
.bus731,
.bus732,
.bus733,
.bus734,
.bus735,
.bus736,
.bus737,
.bus738,
.bus749,
.bus751,
.bus752,
.bus754,
.bus756,
.bus757,
.bus758,
.bus759,
.bus760,
.bus776,
.bus778,
.bus779,
.bus780,
.bus781,
.bus782,
.bus783,
.bus784,
.bus785,
.bus788,
.bus789,
.bus827,
.bus828,
.bus829,
.bus830,
.bus833,
.bus834,
.bus835,
.bus836,
.bus841,
.bus862,
.bus863,
.bus864,
.bus891,
.bus894,
.bus896,
.bussb50,
.bussb51,
.bussb52,
.bussb53,
.bussb55,
.bussb57,
.bussb59,
.bussb85,
.busne1,
.busne2,
.busne3,
.busne4,
.busne5,
.busne6,
.busne7,
.busne8 {
  background-color: #818284;
  color: white;
}

.u70 {
  background-color: #5badce;
  color: white;
}
.u71 {
  background-color: #41c8f4;
  color: white;
}
.u72 {
  background-color: #21bec6;
  color: white;
}
.u73 {
  background-color: #416ab3;
  color: white;
}
.u74 {
  background-color: #282680;
  color: white;
}
.u75 {
  background-color: #0099c7;
  color: white;
}
.u76 {
  background-color: #006cb7;
  color: white;
}
.u77 {
  background-color: #6a93cc;
  color: white;
}
.u78 {
  background-color: #00a6e9;
  color: white;
}
.u79 {
  background-color: #00a99d;
  color: white;
}
.u83 {
  background-color: #16479f;
  color: white;
}

/* RRX */
.re1, .re5 {
  background-color: #FF8C00;  /* orange-ish background */
  color: black;
}
```

**Comment by KristjanESPERANTO** [comment]
Thanks very much! 🙂 I have adopted your changes and also picked out the right colors for the bus lines. They aren't all grey. I found out the line colors via: https://interaktiv-netzkarte.rheinbahn.de/

**Comment by Dom1n1c** [comment]
Whoop, thank you
