### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by Specks8553** [KristjanESPERANTO/MMM-PublicTransportHafas#136]
On installtion i get the following error after running 

npm install --omit=dev

> mmm-publictransporthafas@2.0.1 prepare
> husky install

sh: 1: husky: not found
npm ERR! code 127
[2023-02-18T12_09_29_373Z-debug-0.log](https://github.com/KristjanESPERANTO/MMM-PublicTransportHafas/files/10774172/2023-02-18T12_09_29_373Z-debug-0.log)

npm ERR! path /home/adrian/MagicMirror/modules/MMM-PublicTransportHafas
npm ERR! command failed
npm ERR! command sh -c -- husky install

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/adrian/.npm/_logs/2023-02-18T12_09_29_373Z-debug-0.log

I attached the log file

**Comment by KristjanESPERANTO** [comment]
Your npm is version 8.x, this is a legacy branch. Please upgrade to version 9.x and try again.

**Comment by Specks8553** [comment]
Many thanks for the quick reply. The Problem persists after updating npm to v9.5.0. I added the new log.
[2023-02-18T14_23_37_832Z-debug-0.log](https://github.com/KristjanESPERANTO/MMM-PublicTransportHafas/files/10774489/2023-02-18T14_23_37_832Z-debug-0.log)

**Comment by KristjanESPERANTO** [comment]
Does it make a difference if you run `npm i` instead of `npm install --omit=dev`?

**Comment by Specks8553** [comment]
This fixed it

**Comment by KristjanESPERANTO** [comment]
Nice :slightly_smiling_face: I've made an adjustment so others don't stumble across the same problem.
Have fun with your mirror!
