### ISSUE TITLE
changing distances and orientation

### ISSUE THREAD

**Issue by onkelbobby** [KristjanESPERANTO/MMM-PublicTransportHafas#137]
First of all Thank your for further developing and maintaining this moduel. I used and older version from raywo up to now but changed to your updated fork just lately.

I got everything perfectly working the only thing I cannot manage is the identical orientation of the line symbols. As you see from the picture I'm using the same module 3 times for displaying the departures of 3 different stops in my neighborhood. Due to my personal design preferences all moduels are the aligned to the right hand side of my mirror. Can you tell me what I have to modify to get a nice left-aligned orientation of all line symbols as well as of the destination names within the particulat columns? I tried to symbolize it with the lines and arros in  the picture below.

Thank you
Ben
![hafas2](https://github.com/KristjanESPERANTO/MMM-PublicTransportHafas/assets/6854533/2d2b059a-71e6-4f5b-ba46-c95601dd7c09)

**Comment by KristjanESPERANTO** [comment]
Oh, I just saw your issue. Can you provide me with your configuration of the module? That would make it a little easier for me.

**Comment by KristjanESPERANTO** [comment]
Basically it's because you showed the platform on the first one and not on the others. I'll try to take a look in the next few days.

**Comment by KristjanESPERANTO** [comment]
I've got a pretty good result by adding this to my custom.css:

```css
.mmm-pth-time-cell {
  width: 20%; 
}

td:has(.mmm-pth-sign) {
  width: 20%; 
}
```

Let me know if this works for you to. And feel free to reopen the issue if not.
