### ISSUE TITLE
Error: "request to https://reiseauskunft.bahn.de/bin/mgate.exe?checksum=.... failed, reason: socket hang up

### ISSUE THREAD

**Issue by spxhub** [KristjanESPERANTO/MMM-PublicTransportHafas#138]
I recently installed multiple instances of the MMM-PublicTransportHafas with different profiles. Everything is working so far, but every now and then one or more of the modules configured with the db-profile throws an error like "request to https://reiseauskunft.bahn.de/bin/mgate.exe?checksum={long hash here} failed, reason: socket hang up". (Never happens with other profiles.) The failing modules have different stationIDs.

Then, after 120sec, it works again (With the next update). Changing the "updateEvery"-parameter to 180sec doesn't help.

Any suggestions?

Thanks!

**Comment by KristjanESPERANTO** [comment]
Hi :slightly_smiling_face: How many instances of the module are we talking about? Can you share your config? Can you be more specific about "but every now and then"? Once a day? Once a week?

**Comment by spxhub** [comment]
Hey, its like four instances with one profile vbb and three profiles of db. Message occures like every second or third update of a module. So like every 4 minutes or so per module (except for the vbb profile). But I think now its nothing to do with the number of modules since it occures also with the first db profiled module I added.

But I've just discovered something else: When I disabled two of my three pages of the MMM-Carousel module and only keep the one page with the MMM-PublicTransportHafas modules then the error seems never to occure.
I have to look deeper into this but it seems that it may be related to MMM-Carousel.

**Comment by KristjanESPERANTO** [comment]
That's interesting. Can you please share a minimal configuration with which the error occurs?

**Comment by spxhub** [comment]
Well, this is odd! I've tried to revert to the above mentioned setup but couldn't reproduce the error. 
I've had made some changes outside of MM like activating dtoverlay=vc4-kms-v3d since then.
But even reverting that only slows down MM and have some of the MMM-PublicTransportHafas modules stuck at "...loading" for an indefinite amount of time but not giving the error again.

So I close here. Maybe come back if somehow this error reoccures in a reproduceable manner.

Anyhow, thanks for this beautiful module! ;-)
