### ISSUE TITLE
Changing hafasclient-profile to SBB causes "CGI_READ_FAILED"

### ISSUE THREAD

**Issue by Nattinger** [KristjanESPERANTO/MMM-PublicTransportHafas#14]
Hi there. This is a follow up to [this issue](https://github.com/public-transport/hafas-client/issues/228)

After performing a clean install for this fork and implementing it into Magic Mirror the connections show up as normal. When changing the hafas-client from the default "db" to "sbb" and adapting the station-id accordingly the module shows "CGI_READ_FAILED" after restarting MagicMirror.

After changing it back to "db" it shows up again normally.

Have i forgotten to change something else?

I already tried chaning the default config (MMM-PublicTransportHafas.js) without any success.

Best Regards
Nasim

**Comment by KristjanESPERANTO** [comment]
Hej Nasim, please show your config of the module. This makes it easier for me to look for the error.

**Comment by Nattinger** [comment]
> Hej Nasim, please show your config of the module. This makes it easier for me to look for the error.

config.js
`/* Magic Mirror Config Sample
*
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "192.168.0.176", 	// Address to listen on, can be:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/", 	// The URL path where MagicMirror is hosted. If you are using a Reverse proxy
					// you must set the sub path here. basePath must end with a /
	ipWhitelist: [], 	// Set [] to allow all IP addresses
															// or add a specific IPv4 of 192.168.1.5 :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
															// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "de",
	locale: "de_CH",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
	// local for armv6l processors, default
	//   starts serveronly and then starts chrome browser
	// false, default for all NON-armv6l devices
	// true, force serveronly mode, because you want to.. no UI on this device

modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "MMM-PublicTransportHafas",
			position: "top_right",
			
			config: {
			  // Departures options
			  stationID: "8503202",                   // Replace with your stationID!
			  stationName: "Thalwil",   // Replace with your station name!
			  direction: "",                    // Show only departures heading to this station. (A station ID.)
			  excludedTransportationTypes: [],  // Which transportation types should not be shown on the mirror? (comma-separated list of types) possible values: "tram", "bus", "suburban", "subway", "regional" and "national"
			  ignoredLines: [],                 // Which lines should be ignored? (comma-separated list of line names)
			  timeToStation: 10,   
			  
		  
			  // Look and Feel
			  displayLastUpdate: true,           // Display the last time of module update.
			  maxUnreachableDepartures: 0,      // How many unreachable departures should be shown?
			  maxReachableDepartures: 32,        // How many reachable departures should be shown?
			  showColoredLineSymbols: true,     // Want colored line symbols?
			  customLineStyles: "",             // Prefix for the name of the custom css file. ex: Leipzig-lines.css (case sensitive)
			  showOnlyLineNumbers: false,       // Display only the line number instead of the complete name, i. e. "11" instead of "STR 11"
			  showTableHeadersAsSymbols: true,  // Table Headers as symbols or text?
			  useColorForRealtimeInfo: true    // Want colored real time information (timeToStation, early)?
			},
			
		  },
{
		module: "MMM-OpenmapWeather",
		position: "bottom_left",	// This can be any of the regions.
									// Best results in left or right regions.
		config: {
			// See 'Configuration options' for more information.
			location: "Thalwil, CH",
			locationID: "2658388", //Location ID from http://openweathermap.org/help/city_list.txt
			appid: "861279344ed82176398788675f171e74",  //openweathermap.org API key
      			colorIcon: true
		}
	}
			]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
`
MMM-PublicTransportHafas.js ` /*
  * Update by AgP42 the 18/07/2018
  * 
  * Modification added : 
  * - Management of a PIR sensor with the module MMM-PIR-Sensor (by PaViRo). In case PIR module detect no user, 
  * the update of the ToDoIst is stopped and will be requested again at the return of the user
  * - Management of the "module.hidden" by the core system : same behaviour as "User_Presence" by the PIR sensor
  * - Possibility to add the last update time from server at the end of the module. 
  * This can be configured using "displayLastUpdate" and "displayLastUpdateFormat"
  * */

"use strict";

//UserPresence Management (PIR sensor)
var UserPresence = true; //true by default, so no impact for user without a PIR sensor

Module.register("MMM-PublicTransportHafas", {

  // default values
  defaults: {
    // Module misc
    name: "MMM-PublicTransportHafas",
    hafasProfile: "sbb",                 // Which HAFAS profile should be used?
    hidden: false,
    updatesEvery: 120,                  // How often should the table be updated in s?

    // Header
    headerPrefix: "",
    headerAppendix: "",

    // Display last update time
    displayLastUpdate: false,           // Add or not a line after the tasks with the last server update time
    displayLastUpdateFormat: 'dd - HH:mm:ss', // Format to display the last update. See Moment.js documentation for all display possibilities

    // Departures options
    direction: "",                      // Show only departures heading to this station. (A station ID.)
    ignoredLines: [],                   // Which lines should be ignored? (comma-separated list of line names)
    excludedTransportationTypes: [],    // Which transportation types should not be shown on the mirror? (comma-separated list of types) possible values: "tram", "bus", "suburban", "subway", "regional" and "national"
    timeToStation: 10,                  // How long do you need to walk to the Station? (in minutes)
    timeInFuture: 40,                   // Show departures for the next *timeInFuture* minutes.

    // Look and Feel
    marqueeLongDirections: true,        // Use Marquee effect for long station names?
    replaceInDirections: {},            // key-value pairs which are used to replace `key` by `value` in the displayed directions
    showColoredLineSymbols: true,       // Want colored line symbols?
    useColorForRealtimeInfo: true,      // Want colored real time information (timeToStation, early)?
    showAbsoluteTime: true,             // How should the departure time be displayed? "15:10" (absolute) or "in 5 minutes" (relative)
    showTableHeaders: true,             // Show table headers?
    showTableHeadersAsSymbols: true,    // Table Headers as symbols or written?
    tableHeaderOrder: [ "time", "line", "direction" ], // In which order should the table headers appear? (add "platform" if you like)
    maxUnreachableDepartures: 0,        // How many unreachable departures should be shown?
    maxReachableDepartures: 7,          // How many reachable departures should be shown?
    fadeUnreachableDepartures: true,
    fadeReachableDepartures: true,
    fadePointForReachableDepartures: 0.25,
    customLineStyles: "",               // Prefix for the name of the custom css file. ex: Leipzig-lines.css (case sensitive)
    showOnlyLineNumbers: false          // Display only the line number instead of the complete name, i. e. "11" instead of "STR 11"
  },


  start: function () {
    Log.info("Starting module: " + this.name + " with identifier: " + this.identifier);
    
    this.ModulePublicTransportHafasHidden = false; // By default we display the module (if no carousel or other module)
    this.updatesIntervalID = 0;       // To stop and start auto update for each module instance
    this.lastUpdate = 0;              // Timestamp of the last module update. set at 0 at start-up

    this.departures = [];
    this.initialized = false;
    this.error = {};

    this.sanitzeConfig();

    if (!this.config.stationID) {
      Log.error("stationID not set! " + this.config.stationID);
      this.error.message = this.translate("NO_STATION_ID_SET");

      return;
    }

    let fetcherOptions = {
      identifier: this.identifier,
      hafasProfile: this.config.hafasProfile,
      stationID: this.config.stationID,
      timeToStation: this.config.timeToStation,
      timeInFuture: this.config.timeInFuture,
      direction: this.config.direction,
      ignoredLines: this.config.ignoredLines,
      excludedTransportationTypes: this.config.excludedTransportationTypes,
      maxReachableDepartures: this.config.maxReachableDepartures,
      maxUnreachableDepartures: this.config.maxUnreachableDepartures
    };

    this.sendSocketNotification("CREATE_FETCHER", fetcherOptions);
  },

  
  //Modif AgP42 - 12/07/2018
  suspend: function() {  // Core function called when the module is hidden
    this.ModulePublicTransportHafasHidden = true; // Module hidden
    // Log.log("Function suspend - Module PublicTransportHafas is hidden " + this.config.stationName);
    this.GestionUpdateIntervalHafas(); // Call the function which manages all the cases
  },
  
  resume: function() {  // Core function called when the module is displayed
    this.ModulePublicTransportHafasHidden = false;
    // Log.log("Function working - Module PublicTransportHafas is displayed " + this.config.stationName);
    this.GestionUpdateIntervalHafas();  
  },

  notificationReceived: function(notification, payload) {
    if (notification === "USER_PRESENCE") { // Notification sent by the MMM-PIR-Sensor module. See its doc.
      // Log.log("NotificationReceived USER_PRESENCE = " + payload);
      UserPresence = payload;
      this.GestionUpdateIntervalHafas();
    }
  },
  
  GestionUpdateIntervalHafas: function() {
    if (UserPresence === true && this.ModulePublicTransportHafasHidden === false){ // Make sure to have a user present in front of the screen (PIR sensor) and that the module is displayed
      var self = this;
      // Log.log(this.config.stationName + " is displayed and user present! Update it");
  
      // Update now and start again the update timer
      this.startFetchingLoop(this.config.updatesEvery);

    }else{ // (UserPresence = false OU ModulePublicTransportHafasHidden = true)
      // Log.log("No one is watching: Stop the update!" + this.config.stationName);
      clearInterval(this.updatesIntervalID); // Stop the current update interval
      this.updatesIntervalID = 0; // Reset the variable
    }
  },

  getDom: function () {
    let domBuilder = new PTHAFASDomBuilder(this.config);

    if (this.hasErrors()) {
      return domBuilder.getSimpleDom(this.error.message);
    }

    if (!this.initialized) {
      return domBuilder.getSimpleDom(this.translate("LOADING"));
    }

    let headings = {
      time: this.translate("PTH_DEPARTURE_TIME"),
      line: this.translate("PTH_LINE"),
      direction: this.translate("PTH_TO"),
      platform: this.translate("PTH_PLATFORM")
    };

    let noDeparturesMessage = this.translate("PTH_NO_DEPARTURES");

    var wrapper = domBuilder.getDom(this.departures, headings, noDeparturesMessage);

    // display the update time at the end, if defined so by the user config
    if(this.config.displayLastUpdate){

      var updateinfo = document.createElement("div");
      updateinfo.className = "xsmall light align-left";
      updateinfo.innerHTML = "Update : " + moment.unix(this.lastUpdate).format(this.config.displayLastUpdateFormat);
      wrapper.appendChild(updateinfo);
    }

    return wrapper;
  },


  getStyles: function () {
    let styles = [
      this.file("css/styles.css"),
      "font-awesome.css"
    ];

    if (this.config.customLineStyles !== "") {
      let customStyle = "css/" + this.config.customLineStyles + "-lines.css";
      styles.push(this.file(customStyle));
    }

    return styles;
  },


  getScripts: function () {
    return [
      "moment.js",
      this.file("core/PTHAFASDomBuilder.js"),
      this.file("core/PTHAFASTableBodyBuilder.js")
    ];
  },


  getTranslations: function() {
    return {
      en: "translations/en.json",
      de: "translations/de.json"
    };
  },


  socketNotificationReceived: function (notification, payload) {
    if (!this.isForThisStation(payload)) {
      return;
    }

    switch (notification) {
      case "FETCHER_INITIALIZED":
        this.initialized = true;
        this.startFetchingLoop(this.config.updatesEvery);

        break;

      case "DEPARTURES_FETCHED":
      
        //AgP            
        if(this.config.displayLastUpdate){
          this.lastUpdate = Date.now() / 1000 ; //save the timestamp of the last update to be able to display it    
        }
      
        Log.log("TransportHafas update OK, station : " + this.config.stationName + " at : " 
          + moment.unix(this.lastUpdate).format(this.config.displayLastUpdateFormat)); 
      
        //this.sendNotification("SHOW_ALERT",{type:"notification",message:"Update Transport Berlin recue"});
     
        // reset error object
        this.error = {};
        this.departures = payload.departures;
        this.updateDom(2000);
        this.sendNotification('TRANSPORT_HAFAS', payload.departures)
        break;

      case "FETCH_ERROR":
        this.error = payload.error;
        this.departures = [];
        this.updateDom(2000);

        break;
    }
  },


  isForThisStation: function (payload) {
    return payload.identifier === this.identifier;
  },


  sanitzeConfig: function () {
    if (this.config.updatesEvery < 30) {
      this.config.updatesEvery = 30;
    }

    if (this.config.timeToStation < 0) {
      this.config.timeToStation = 0;
    }

    if (this.config.timeInFuture < this.config.timeToStation + 30) {
      this.config.timeInFuture = this.config.timeToStation + 30;
    }

    if (this.config.maxUnreachableDepartures < 0) {
      this.config.maxUnreachableDepartures = 0;
    }

    if (this.config.maxReachableDepartures < 0) {
      this.config.maxReachableDepartures = this.defaults.maxReachableDepartures;
    }
  },


  startFetchingLoop: function(interval) {
    // start immediately ...
    this.sendSocketNotification("FETCH_DEPARTURES", this.identifier);

    // ... and then repeat in the given interval
    
    // Log.log("Hello, update module Transport requested! (non-recurring)");
    // this.sendNotification("SHOW_ALERT",{type:"notification",message:"Update Transport Berlin requested"});
    
    if (this.updatesIntervalID === 0){//if this instance as no auto update defined, then we create one. Otherwise : nothing.
    
      this.updatesIntervalID = setInterval(() => {
        this.sendSocketNotification("FETCH_DEPARTURES", this.identifier);
      }, interval * 1000);
    
    }
    
  },


  hasErrors: function () {
    return (Object.keys(this.error).length > 0);
  },
});

`


Hope this helps out :)

**Comment by Nattinger** [comment]
> Hej Nasim, please show your config of the module. This makes it easier for me to look for the error.

Hi There. Thanks for reaching out. I had to delete the old comment since the quoting was messed up (my bad).

If you don't mind... I'll attach a [onedrive link.](https://1drv.ms/u/s!Aj3Oz9RXvd5cgoga6_gCt4VJ0GGYBg?e=n6uAj2)

Best Regards
Nasim

**Comment by KristjanESPERANTO** [comment]
That's interesting. I suppose this is a problem in the sbb profile. I'll try to take a closer look at it in the next few days to get to the bottom of it.

**Comment by KristjanESPERANTO** [comment]
I have added my findings to the [hafas-client issue](https://github.com/public-transport/hafas-client/issues/228). Let's see what @derhuerst says about it.

Please delete your onedrive files. They contain your openweather API key.

**Comment by Nattinger** [comment]
Hi Kristjan

Thank you for your research.

Like you advised, i have deleted the onedrive folder. Thanks for pointing it out :)

Best Regards

**Comment by KristjanESPERANTO** [comment]
"Currently people are clarifying if the SBB HAFAS endpoint has been disabled permanently." 
https://github.com/public-transport/hafas-client/pull/246

So unfortunately, the problem cannot be fixed. I hereby close this issue.
