### ISSUE TITLE
Error in PTHAFASTableBodyBuilder.js

### ISSUE THREAD

**Issue by MarkusLange** [KristjanESPERANTO/MMM-PublicTransportHafas#16]
in Line 255 console.log(product);

blocks working of MMM-PublicTransportHafas js mockup console.log is not a function

**Comment by KristjanESPERANTO** [comment]
Interesting that this is causing problems for you. `console.log()` is a function that every browser (also electron) can do out of the box. Anyway, this is an old forgotten test entry and I just removed it.

Thanks for the hint! :slightly_smiling_face:
