### ISSUE TITLE
timeFormat in config being ignored

### ISSUE THREAD

**Issue by elgrwo** [KristjanESPERANTO/MMM-PublicTransportHafas#164]
**Bug description**
Even though I have `timeFormat: 24,` set in the general MagicMirror config, it shows am/pm in the departure time.

One part of the problem may be:
`dayjs.locale(config.language);`

Or 
`this.file(`node_modules/dayjs/locale/${config.language}.js`),`

**Comment by KristjanESPERANTO** [comment]
Interesting. Please try to add `language: "de",` to the general MagicMirror config.

**Comment by elgrwo** [comment]
Changing the language did change the time format, however it also changed the language 😭 

Is there no way to keep my MagicMirror config in English but only change the timeFormat? My German is not very good and I would really prefer to keep the settings that way.

**Comment by KristjanESPERANTO** [comment]
Since we no longer use momentjs here, the value for `timeFormat` did not work. I have just fixed it. Now it also works with the combination `language: "en"` and `timeFormat: 24` :slightly_smiling_face:

Let me know if it works for you too.

**Comment by elgrwo** [comment]
> Since we no longer use momentjs here, the value for `timeFormat` did not work. I have just fixed it. Now it also works with the combination `language: "en"` and `timeFormat: 24` 🙂
> 
> Let me know if it works for you too.

yes, it works!! even with my strange combination 😉 

thanks for your fantastic support, I really appreciate it!!
