### ISSUE TITLE
How to resize whole output

### ISSUE THREAD

**Issue by drtorchwood** [KristjanESPERANTO/MMM-PublicTransportHafas#172]
Hi, 

I really like the new design of this branch. I have only one question: How can easily decrease the size of the whole visual? Is there a global option that only applies to this module?

Best, 
jan

**Comment by KristjanESPERANTO** [comment]
There is no global option. You have to tweak your `custom.css`.

Try this and add the following lines to your `custom.css`:

```css
.mmm-pth-table {
  font-size: 1.5rem;
}
```

**Comment by drtorchwood** [comment]
Thanks. That was the proper hint. I now use the `zoom` parameter, which also worked. Previously, I thought that I have to change the module's css file.

**Comment by KristjanESPERANTO** [comment]
I'm glad it helped you :slightly_smiling_face:

It is advisable not to touch the modules code, otherwise you will have problems updating them later. That's what custum.css is for.
