### ISSUE TITLE
Fixed width and hight for Line-Symbols? 

### ISSUE THREAD

**Issue by xIExodusIx** [KristjanESPERANTO/MMM-PublicTransportHafas#173]
**Is your feature request related to a problem? Please describe.**

the width of a Line-Symbol jumps from width (e.g. (Bus) 275 to (Bus) 9). Would be nice when the width of the Symbol for Bus 9 is the same as for Bus 275. 

**Describe the solution you'd like**

Is it possible to assign a fixed width and height to the line symbols in the "config.js" or the "xxx-lines.css"?

**Describe alternatives you've considered**

**Additional context**

**Comment by KristjanESPERANTO** [comment]
Try this in your `custom.css`:

```css
td:has(.mmm-pth-sign) {
  width: 15%; 
}
```

**Comment by xIExodusIx** [comment]
Hello Kristjan,
I will insert it in the "custom.css" and test it.

Thank you for your help.

**Comment by KristjanESPERANTO** [comment]
You're welcome 🙂 I am closing this issue. Let me know if it doesn't work.

**Comment by xIExodusIx** [comment]
Unfortunately, this does not work as hoped. The Bus-Signs have all the same width. We hav a lot of public-traffic-sings in Hamburg: The most of them (without the Bus-Signs) you can find here: https://de.wikipedia.org/wiki/Hamburger_Verkehrsverbund#:~:text=Der%20Hamburger%20Verkehrsverbund%20ist%20ein%20Verkehrs-
The Bus-Signs are displayd in MMM-HH-LocalTransport but I like your Module it has more and better Infos, for my Station I need only Bus-Signs and RB81 (Regional-Bahn) this will change in a few years to S4 (S-Bahn) the S4 Sign will be pink. :-(

**Comment by xIExodusIx** [comment]
Maybe you can instruct me how to build the hamburg-lines.css so I can try to build it not only for me also for all other MM Owners in Hamburg if someone of them use your Module. :-)

**Comment by KristjanESPERANTO** [comment]
Are you using the customLineStyles for Hamburg?

```js
		{
			module: "MMM-PublicTransportHafas",
			position: "top_left",
			config: {
				stationID: "8002549",
				stationName: "Hamburg HBF",
				customLineStyles: "hamburg",
				...
```

I just updated the CSS for Hamburg a bit. My test looks like that:

![Screenshot from 2024-10-05 23-48-58](https://github.com/user-attachments/assets/3dde01bc-46c4-4604-a0dc-26560c055d02)

Please update the module, use ttyle for hamburg and let me know if something is missing. Maybe with screeshots and the id of the station.

**Comment by xIExodusIx** [comment]
Thanks a lot that looks great, and I'm satisfied now, thank you very much. I use a station-id near my home, there are only  two bigger Busses-stations with a lot of bus-lines and one regional-train station, so I don't need ferrys-lines and underground-lines. The regionaltrain station will in some time change to a  "normal" public train station that then change the name from RB81 to S4.
Again thank you very much.

**Comment by KristjanESPERANTO** [comment]
I'm glad to have helped you and thank you for the suggestion to improve the Hamburg CSS. All other Hamburg users will now also benefit from this :slightly_smiling_face:
