### ISSUE TITLE
Latest update breakes MariusEng / MMM-Netatmo

### ISSUE THREAD

**Issue by fnsign** [KristjanESPERANTO/MMM-PublicTransportHafas#18]
**Describe the bug**
After updating your module to the latest version,  the MMM-Netatmo (fork fromMariusEng https://github.com/MariusEng/MMM-Netatmo) completely dissapears from the display. There is no error code or similar, it is completly not visible any more.

**To Reproduce**
1. go to Magic ~/MagicMirror/modules/MMM-PublicTransportHafas
2. git pull
3. npm install
4. reboot

**Expected behavior**
The MMM-Netatmo module should still remain visible

**Screenshots**
-

**Additional context**
-

**Comment by fnsign** [comment]
I think I found where the problem is (I hope so from my very basic understanding)
In MMM-PublicTransportHafas.js you recently changed the variable declarations from var to let.
Im not sure, but the declaration of userPresensence should be globally availabe, and not locally within the function. (this is at least what I understood what var vs. let means). 
When I change
`
let UserPresence = true; //true by default, so no impact for user without a PIR sensor
`

back to
`
var UserPresence = true; //true by default, so no impact for user without a PIR sensor
`
the MMM-Netatmo module appears again. Could you fix that?

**Comment by KristjanESPERANTO** [comment]
Sorry, I didn't get a notification about your issue. I'll try to see it soon :slightly_smiling_face:

**Comment by KristjanESPERANTO** [comment]
I still don't understand why this is causing problems with MMM-Netatmo. This module doesn't use the variable `UserPresence`. Even so, I made the change you suggested :slightly_smiling_face:
