### ISSUE TITLE
Displaying ring lines in both directions

### ISSUE THREAD

**Issue by AlbMarc** [KristjanESPERANTO/MMM-PublicTransportHafas#19]
**Ring lines**
Hi.
In Heidelberg, there is a tram ring line, which surrounds the entire region in 2 h. I would be interested to see just one direction. Now I see both directions that would take me 10 min and 1:50 h to my destination.

Because it is a ring line Hafas considers them the same line that reaches the same destination.

Is there a way to distinguish them?

**Screenshots**
![HafasClientBug](https://user-images.githubusercontent.com/16539374/136815713-a4a1e153-482e-4538-a950-8f2384e155d7.png)

Red arrow - Wrong direction. Green arrow - Right direction.

**Comment by KristjanESPERANTO** [comment]
Interesting that the same destination is displayed for both. Please show your configuration of the module so that I can try it out.

Filters for platforms do not exist yet.

**Comment by KristjanESPERANTO** [comment]
I have a dirty solution which will break every time after an update of this module. But for now I have no better one and it should work for you for this one case.

Replace in the file `/core/PTHAFASTableBodyBuilder.js` the line 25:

Before:

`tBody.appendChild(row);`

After:

`if (!(departure.direction == 'Alter OEG-Bahnhof, Weinheim' && departure.stop.id == '511016')) { tBody.appendChild(row); }`

**Comment by KristjanESPERANTO** [comment]
By the way: The hafas API from VRN does not provide any platform information for your station.
