### ISSUE TITLE
No more display :(

### ISSUE THREAD

**Issue by Bluefish67** [KristjanESPERANTO/MMM-PublicTransportHafas#20]
Hello, for days I have the following ad.
"There are no reachable stations".
The whole thing was running for months without any problems.
Has something changed on the module?

Sorry for my bad Englisch....

**Comment by KristjanESPERANTO** [comment]
There are currently no direct trips from "Drosselberg, Erfurt" to "Anger, Erfurt". Remove the direction line from your config and you will see, that the module is working.

**Comment by Bluefish67** [comment]
Thanks for the answer.
Can it be that the station numbers have changed?
I will continue to monitor this.

**Comment by KristjanESPERANTO** [comment]
The station IDs haven't changed. But because SEV lines are showing, I suspect it is just a temporary situation.
