### ISSUE TITLE
Latest version 1.2.0 re-introduces issue #18

### ISSUE THREAD

**Issue by fnsign** [KristjanESPERANTO/MMM-PublicTransportHafas#34]
The last update to v1.2.0 re-introduces the problem with the MMM-Netatmo module, reported in detail in issue #18.
I could reproduce it by changing the declaration from `let` back to` var`

**Comment by KristjanESPERANTO** [comment]
Sorry that this happened again. In the fork you mentioned in #18, the variable `UserPresence` is used, that's the problem. I have changed it back to `var`, but actually there should be another solution here. But for that you would have to change all the modules that work with this variable.

Just for interest: why are you using a fork of MMM-Netatmo and not the upstream project, which is obviously still active: https://github.com/CFenner/MMM-Netatmo

**Comment by fnsign** [comment]
Thanks a lot for fixing the issue so quickly!
The reason, why I use that specific fork is that I'm running two netatmo stations in two different houses and that module allows for selecting which station should be displayed on MM (`deviceNumber`). I searched quite intensively, but this fork was the only one that met my requirements. You can have multiple stations under one Netatmo account, but the @CFenner module (and most of other forks) pick the first installed station only.

**Comment by CFenner** [comment]
Actually, I paused the development for quite some time. Just recently I added the ability to load all stations of an account. Stations from different accounts are not supported, but one may invite guest user to a station. Maybe that helps.
