### ISSUE TITLE
Multiple instances crashing

### ISSUE THREAD

**Issue by 111wolf111** [KristjanESPERANTO/MMM-PublicTransportHafas#43]
Hi,
I'm from Salzburg and am useing the svv databse.

I'm having problems running 2 instances. It seems when I add another station errors come up and the pi seems to crash, I can't even SSL into the pi to do anything.

I removed one and am useing just one station at the moment and all seems to work fine,

Could you please look into it, if you need any more info please let me know.

Thanks in advance.

**Comment by KristjanESPERANTO** [comment]
Several modules work for me without any problems. Please show the configuration of your two module instances.

**Comment by 111wolf111** [comment]
sure here it is, it use to work no problem, we moved and I haven't used the mirror for a while and did all updates etc and it worked for a few days and now crashes.
Maybe it has something to do with SVV.
'
                {
                        module: "MMM-PublicTransportHafas",
                        position: "top_right",
                        config: {
// Departures options
                                hafasProfile: "svv",                            // Hafas Peofile to use
                                stationID: "455086900",                         // Replace with your stationID!
                                stationName: "Fadingerstrasse",         // Replace with your station name!
                                direction: "455001800",                                 // Show only departures heading to this station. (A station ID.)
                                excludedTransportationTypes: [],                // Which transportation types should not be shown on the mirror? (comma-separated list of types) possible values: "tram", "bus", "$                                ignoredLines: [],                               // Which lines should be ignored? (comma-separated list of line names)
                                timeToStation: 5,                               // How long do you need to walk to the next Station?
                                timeInFuture: 180,                              // How much into the future to show (in minutes)
// Look and Feel
                                updatesEvery: 60,                               // Update interval
                                displayLastUpdate: true,                        // Display the last time of module update.
                                maxUnreachableDepartures: 1,                    // How many unreachable departures should be shown?
                                fadeUnreachableDepartures: true,                // Fade out unreachable departures
                                maxReachableDepartures: 7,                      // How many reachable departures should be shown?
                                fadeReachableDepartures: false,                 // Fade out reachable departures
                                showColoredLineSymbols: true,                   // Want colored line symbols?
                                customLineStyles: "",                           // Prefix for the name of the custom css file. ex: Leipzig-lines.css (case sensitive)
                                showOnlyLineNumbers: true,                      // Display only the line number instead of the complete name, i. e. "11" instead of "STR 11"
                                showTableHeadersAsSymbols: true,                // Table Headers as symbols or text?
                                tableHeaderOrder: [ "line", "direction", "time" ],
                                useColorForRealtimeInfo: true,                  // Want colored real time information (timeToStation, early)?
                                showAbsoluteTime: true,                         // True time or absolute
                                displayLastUpdateFormat: 'HH:mm:ss',            // Time format of last update
                                showWarningRemarks: false


                        }
                },

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//              {
//                      module: "MMM-PublicTransportHafas",
//                      position: "top_right",
//                      config: {
// Departures options
//                              hafasProfile: "svv",                            // Hafas Peofile to use
//                              stationID: "455045600",                         // Replace with your stationID!
//                              stationName: "Parsch",                          // Replace with your station name!
//                              direction: "455045700",                         // Show only departures heading to this station. (A station ID.)
//                              excludedTransportationTypes: [],                // Which transportation types should not be shown on the mirror? (comma-separated list of types) possible values: "tram", "bus", "$//                              ignoredLines: [],                               // Which lines should be ignored? (comma-separated list of line names)
//                              timeToStation: 13,                              // How long do you need to walk to the next Station?
//                              timeInFuture: 360,                              // How much into the future to show (in minutes)
// Look and Feel
//                              marqueeLongDirections: true,                     // Scroll long names
//                              updatesEvery: 900,                              // Update interval
//                              displayLastUpdate: true,                        // Display the last time of module update.
//                              maxUnreachableDepartures: 1,                    // How many unreachable departures should be shown?
//                              fadeUnreachableDepartures: true,                // Fade out unreachable departures
//                              maxReachableDepartures: 3,                      // How many reachable departures should be shown?
//                              fadeReachableDepartures: false,                 // Fade out reachable departures
//                              showColoredLineSymbols: true,                   // Want colored line symbols?
//                              customLineStyles: "",                           // Prefix for the name of the custom css file. ex: Leipzig-lines.css (case sensitive)
//                              showOnlyLineNumbers: true,                      // Display only the line number instead of the complete name, i. e. "11" instead of "STR 11"
//                              showTableHeadersAsSymbols: true,                // Table Headers as symbols or text?
//                              tableHeaderOrder: [ "line", "platform", "direction", "time" ],
//                              useColorForRealtimeInfo: true,                  // Want colored real time information (timeToStation, early)?
//                              showAbsoluteTime: true,                         // True time or absolute
//                              displayLastUpdateFormat: 'HH:mm:ss',            // Time format of last update
//                              showWarningRemarks: false
//
//                      }
//              },
// 
'

**Comment by KristjanESPERANTO** [comment]
Okay, I'll take a closer look at it by the weekend at the latest 🙂

**Comment by 111wolf111** [comment]
super thanks

**Comment by KristjanESPERANTO** [comment]
Unfortunately, I cannot detect any problem. Both of your configurations work for me without any problems. Which node version do you have? The easiest way to find out is to use `node -v`.

**Comment by 111wolf111** [comment]
Thanks for looking into it so quickly.
Sorry for wasting your time,
I looked into it a bit more before going to work today, I have a feeling it might be my network.
I don't want to waste your time, I have more time to troubleshoot it on the weekend, maybe it has nothing to do with the module.
I will let you know.

**Comment by KristjanESPERANTO** [comment]
No problem. Good luck with the troubleshooting! :slightly_smiling_face:

**Comment by 111wolf111** [comment]
Well I believe I managed to fix it the original problem I think was "fast roaming" in my router settings, after switching it off the pie started keeping it's connection. In the process I managed to screw up either MM install, node.js or pm2 or all 3, so I ended up moving the MM folder and installing everything again and it seems to be fine now.
Sorry again for wating your time, you can close this now.
