### ISSUE TITLE
Help needed for hamburg-lines.css --> no Issue.

### ISSUE THREAD

**Issue by xIExodusIx** [KristjanESPERANTO/MMM-PublicTransportHafas#82]
I used [MMM-HH-LocalTransport](https://github.com/georg90/MMM-HH-LocalTransport) before, that works pretty fine, it uses and needs a GEOfox API-Key to run and display bus lines, but this didn't shows the symbol (RB 81) for the trains. The symbols for the buses are shown correctly like we have it here in Hamburg. Please see https://de.wikipedia.org/wiki/Vorlage:%C3%96PNV_Hamburg. It's a picture called [Hamburg_Bus-Logo.svg](https://de.wikipedia.org/wiki/Datei:Hamburg_Bus-Logo.svg). I tried to load it with the ``hamburg-lines.css``, but I failed.
Could you help?

The second problem I have is that I don't want to see if the bus and/or train is in time (green +0 or gray +?), but I want to see if its to late or more than 0 Minutes to early.

I am not really good in coding, but I try my very best to understand how it all works, and try to solve the problems by myself. But sometimes I need help. Also my English is not really good anymore. School is to far away.

**Comment by KristjanESPERANTO** [comment]
Hi @xIExodusIx :slightly_smiling_face: 

I created a `hamburg-lines.css` with an adjusted bus symbol. In my test environment it looks like this:
![Ekrankopio de 2022-08-29 00-49-51](https://user-images.githubusercontent.com/35647502/187097858-37d842b6-f374-4c70-add2-7a2d79e580c2.png)

Is this how you wanted it?

Does `showAbsoluteTime: false,` in your module config solves your second problem?

**Comment by djzwerg** [comment]
Hi @KristjanESPERANTO and greetings to my former colleague ;-) Thanks for your great work!

I'm not sure whether I have the same issue as @xIExodusIx but the lines won't be coloured in my case, too. Here are my settings (for testing, of course):
![grafik](https://user-images.githubusercontent.com/49948628/190830708-1d3a8a91-c0cd-4256-8f78-70afb17cd92d.png)

And this is the result:
![grafik](https://user-images.githubusercontent.com/49948628/190830725-6d657e59-ee52-4f24-8b68-e3d7de98a96d.png)

**Comment by KristjanESPERANTO** [comment]
Hi former colleague :smile: 

that's a different problem - the value for `customLineStyles` just has to be `"halle"`.

Try this configuration (with some other changes):

```js
    {
      module: "MMM-PublicTransportHafas",
      position: "middle_center",
      config: {
        hafasProfile: "insa",
        stationID: "5067",
        stationName: "Haltestelle Burg Giebichenstein",
        updatesEvery: 30,
        maxUnreachableDepartures: 0,
        maxReachableDepartures: 10,
        timeInFuture: 360,
        timeToStation: 1,
        showAbsoluteTime: false,
        customLineStyles: "halle",
        fadeReachableDepartures: false,
        replaceInDirections: { "Halle (Saale), ": "" },
        showOnlyLineNumbers: true,
        tableHeaderOrder: ["time", "line", "direction", "platform"]
      }
    },
```

![Ekrankopio de 2022-09-17 02-02-34](https://user-images.githubusercontent.com/35647502/190832401-9151ee84-c3e0-46ef-a842-1143c9acc8e3.png)

**Comment by djzwerg** [comment]
Hi @KristjanESPERANTO and thanks for your fast reply! I made the changes and it works without the platforms:
![grafik](https://user-images.githubusercontent.com/49948628/190845594-e5bfffec-c991-47fc-94b2-494250949400.png)

I don't know why they are missing.

Note: I have to change the replacing line to `replaceInDirections: { ", Halle (Saale)": "" },`

**Comment by KristjanESPERANTO** [comment]
@xIExodusIx: I'm closing the issue. If you still have issues, please reopen this one or open a new one :slightly_smiling_face:
